[package]
name = "portpresence"
version = "0.1.0"
edition = "2024"

[dependencies]
discord-rich-presence = "0.2.5"
futures = "0.3.31"
procfs = "0.17.0"
psutil = "5.2.0"
tokio = { version = "1.45.1", features = ["full"] }
